//
//  BleEvent.h
//  TelinkBle
//
//  Created by Thanh Tùng on 06/04/2022.
//  Copyright © 2022 Facebook. All rights reserved.
//

#ifndef BleEvent_h
#define BleEvent_h

#define EVENT_MESH_CONNECT                  @"EVENT_MESH_CONNECT"
#define EVENT_SCANNING_TIMEOUT              @"EVENT_SCANNING_TIMEOUT"
#define EVENT_UNPROVISIONED_DEVICE_FOUND    @"EVENT_UNPROVISIONED_DEVICE_FOUND"
#define EVENT_PROVISIONING_SUCCESS          @"EVENT_PROVISIONING_SUCCESS"
#define EVENT_PROVISIONING_FAILED           @"EVENT_PROVISIONING_FAILED"
#define EVENT_BINDING_SUCCESS               @"EVENT_BINDING_SUCCESS"
#define EVENT_BINDING_FAILED                @"EVENT_BINDING_FAILED"
#define EVENT_NODE_RESET_SUCCESS            @"EVENT_NODE_RESET_SUCCESS"
#define EVENT_NODE_RESET_FAILED             @"EVENT_NODE_RESET_FAILED"
#define EVENT_SET_GROUP_SUCCESS             @"EVENT_SET_GROUP_SUCCESS"
#define EVENT_SET_GROUP_FAILED              @"EVENT_SET_GROUP_FAILED"
#define EVENT_REMOVE_GROUP_SUCCESS          @"EVENT_REMOVE_GROUP_SUCCESS"
#define EVENT_REMOVE_GROUP_FAILED           @"EVENT_REMOVE_GROUP_FAILED"
#define EVENT_SET_SCENE_SUCCESS             @"EVENT_SET_SCENE_SUCCESS"
#define EVENT_SET_SCENE_FAILED              @"EVENT_SET_SCENE_FAILED"
#define EVENT_REMOVE_SCENE_SUCCESS          @"EVENT_REMOVE_SCENE_SUCCESS"
#define EVENT_REMOVE_SCENE_FAILED           @"EVENT_REMOVE_SCENE_FAILED"
#define EVENT_DEVICE_STATUS                 @"EVENT_DEVICE_STATUS"
#define EVENT_DEVICE_ONLINE_STATUS          @"EVENT_DEVICE_ONLINE_STATUS"

#endif /* BleEvent_h */
