export enum BleEvent {
  EVENT_MESH_CONNECT = 'EVENT_MESH_CONNECT',

  EVENT_SCANNING_TIMEOUT = 'EVENT_SCANNING_TIMEOUT',
  EVENT_UNPROVISIONED_DEVICE_FOUND = 'EVENT_UNPROVISIONED_DEVICE_FOUND',
  EVENT_PROVISIONING_SUCCESS = 'EVENT_PROVISIONING_SUCCESS',
  EVENT_PROVISIONING_FAILED = 'EVENT_PROVISIONING_FAILED',
  EVENT_BINDING_SUCCESS = 'EVENT_BINDING_SUCCESS',
  EVENT_BINDING_FAILED = 'EVENT_BINDING_FAILED',

  EVENT_NODE_RESET_SUCCESS = 'EVENT_NODE_RESET_SUCCESS',
  EVENT_NODE_RESET_FAILED = 'EVENT_NODE_RESET_FAILED',

  EVENT_SET_GROUP_SUCCESS = 'EVENT_SET_GROUP_SUCCESS',
  EVENT_SET_GROUP_FAILED = 'EVENT_SET_GROUP_FAILED',
  EVENT_REMOVE_GROUP_SUCCESS = 'EVENT_REMOVE_GROUP_SUCCESS',
  EVENT_REMOVE_GROUP_FAILED = 'EVENT_REMOVE_GROUP_FAILED',

  EVENT_SET_SCENE_SUCCESS = 'EVENT_SET_SCENE_SUCCESS',
  EVENT_SET_SCENE_FAILED = 'EVENT_SET_SCENE_FAILED',
  EVENT_REMOVE_SCENE_SUCCESS = 'EVENT_REMOVE_SCENE_SUCCESS',
  EVENT_REMOVE_SCENE_FAILED = 'EVENT_REMOVE_SCENE_FAILED',

  EVENT_DEVICE_STATUS = 'EVENT_DEVICE_STATUS',
  EVENT_DEVICE_ONLINE_STATUS = 'EVENT_DEVICE_ONLINE_STATUS',
}
